/////////////////
//Robert Salay
//hw 07 - number waves
//3/17/15
//output waves of numbers generated by a user chosen number [1-30]
//using for loops, do loops, and do-while loops
import java.util.Scanner;
public class waves{
    public static void main(String[]args){
        Scanner myScanner = new Scanner(System.in);
        int input = 0;
        System.out.print("Enter a number 1-30: ");
        while (input == 0){
            if (myScanner.hasNextInt()){
                input=myScanner.nextInt();
                if(input < 1 || input > 30){
                    input = 0; //keeps the loop going if user input wasn't proper
                    System.out.print("Enter a number 1-30: ");
                }
            }else{
                String garbage = myScanner.next(); //removes usermade input if it isn't an int
                System.out.print("Enter a number 1-30: ");
            }
        }
        
        System.out.println("FOR LOOP:");
        for(int i = 1; i <= input; i++){
            if (i%2 == 1){
                for(int j = i; j > 0; j--){
                    for(int k = j; k >0; k--){
                        System.out.print(i);
                    }
                    System.out.print("\n");
                }
            }else{
                for(int j = 1; j <= i; j++){
                    for(int k = 1; k <= j; k++){
                        System.out.print(i);
                    }
                    System.out.print("\n");
                }
            }
        }
        System.out.print("\n");
        System.out.println("DO LOOP:");
        int counter = 1;
        while(counter <= input){
            if(counter%2 == 1){
                int counter2 = counter;
                while(counter2 > 0){
                    int counter3 = counter2;
                    while(counter3 >0){
                        System.out.print(counter);
                        counter3 --;
                    }
                    System.out.print("\n");
                    counter2 --;
                }
            }else{
                int counter2 = 1;
                while(counter2 <= counter){
                    int counter3 = 1;
                    while(counter3 <= counter2){
                        System.out.print(counter);
                        counter3++;
                    }
                    System.out.print("\n");
                    counter2++;
                }
            }
            counter ++;
        }
        System.out.print("\n");
        System.out.println("DO WHILE LOOP:");
        counter = 1;
        do{
            if(counter%2 == 1){
                int counter2 = counter;
                do{
                    int counter3 = counter2;
                    do{
                        System.out.print(counter);
                        counter3 --;
                    }while(counter3 >0);
                    System.out.print("\n");
                    counter2 --;
                }while(counter2 > 0);
            }else{
                int counter2 = 1;
                do{
                    int counter3 = 1;
                    do{
                        System.out.print(counter);
                        counter3++;
                    }while(counter3 <= counter2);
                    System.out.print("\n");
                    counter2++;
                }while(counter2 <= counter);
            }
            counter ++;
        }while(counter <= input);
    }
}